"""phase 4 offer snapshots

Revision ID: 221c01c40846
Revises: 28882e61d605
Create Date: 2026-07-31 17:30:34.042606

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "221c01c40846"
down_revision: str | Sequence[str] | None = "28882e61d605"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_authorization_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_product_id", sa.String(length=255), nullable=False),
        sa.Column("merchant_variant_id", sa.String(length=255), nullable=False),
        sa.Column("product_title", sa.String(length=500), nullable=False),
        sa.Column("variant_title", sa.String(length=500), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("shipping_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("landed_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estimated_arrival_days", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("quote_id", sa.String(length=255), nullable=True),
        sa.Column("quote_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estimated_arrival_days IS NULL OR estimated_arrival_days >= 0",
            name="offer_snapshot_arrival_days_nonnegative",
        ),
        sa.CheckConstraint("landed_price >= 0", name="offer_snapshot_landed_price_nonnegative"),
        sa.CheckConstraint("shipping_price >= 0", name="offer_snapshot_shipping_price_nonnegative"),
        sa.CheckConstraint("unit_price >= 0", name="offer_snapshot_unit_price_nonnegative"),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["merchant_authorization_id"], ["merchant_authorizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_offer_snapshots_agent_run_id"), "offer_snapshots", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_offer_snapshots_merchant_authorization_id"),
        "offer_snapshots",
        ["merchant_authorization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_offer_snapshots_merchant_authorization_id"), table_name="offer_snapshots"
    )
    op.drop_index(op.f("ix_offer_snapshots_agent_run_id"), table_name="offer_snapshots")
    op.drop_table("offer_snapshots")
    # ### end Alembic commands ###
