"""phase 2 care setup

Revision ID: ce93b398178e
Revises: 20260731_0001
Create Date: 2026-07-31 16:47:06.769786

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce93b398178e"
down_revision: str | Sequence[str] | None = "20260731_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "beneficiaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("relationship_label", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_beneficiaries_owner_id"), "beneficiaries", ["owner_id"], unique=False)
    op.create_table(
        "merchant_authorizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_key", sa.String(length=40), nullable=False),
        sa.Column("merchant_name", sa.String(length=120), nullable=False),
        sa.Column("merchant_domain", sa.String(length=255), nullable=False),
        sa.Column("preference_rank", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("preference_rank > 0", name="merchant_authorization_rank_positive"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "merchant_key", name="merchant_authorization_owner_key_unique"
        ),
    )
    op.create_index(
        op.f("ix_merchant_authorizations_owner_id"),
        "merchant_authorizations",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "session_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_tokens_expires_at"), "session_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_session_tokens_token_hash"), "session_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_session_tokens_user_id"), "session_tokens", ["user_id"], unique=False)
    op.create_table(
        "supplies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("beneficiary_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("daily_consumption", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("quantity_on_hand", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("safety_buffer_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("daily_consumption > 0", name="supply_daily_consumption_positive"),
        sa.CheckConstraint("quantity_on_hand >= 0", name="supply_quantity_nonnegative"),
        sa.CheckConstraint("safety_buffer_quantity >= 0", name="supply_safety_buffer_nonnegative"),
        sa.ForeignKeyConstraint(["beneficiary_id"], ["beneficiaries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplies_beneficiary_id"), "supplies", ["beneficiary_id"], unique=False
    )
    op.create_table(
        "product_equivalence_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("supply_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["supply_id"], ["supplies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supply_id", "name", name="equivalence_set_supply_name_unique"),
    )
    op.create_index(
        op.f("ix_product_equivalence_sets_supply_id"),
        "product_equivalence_sets",
        ["supply_id"],
        unique=False,
    )
    op.create_table(
        "approved_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equivalence_set_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_authorization_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_product_id", sa.String(length=255), nullable=False),
        sa.Column("merchant_variant_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("pack_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("pack_unit", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pack_quantity > 0", name="approved_variant_pack_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["equivalence_set_id"], ["product_equivalence_sets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["merchant_authorization_id"], ["merchant_authorizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "equivalence_set_id",
            "merchant_authorization_id",
            "merchant_product_id",
            "merchant_variant_id",
            name="approved_variant_exact_identity_unique",
        ),
    )
    op.create_index(
        op.f("ix_approved_variants_equivalence_set_id"),
        "approved_variants",
        ["equivalence_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approved_variants_merchant_authorization_id"),
        "approved_variants",
        ["merchant_authorization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_approved_variants_merchant_authorization_id"), table_name="approved_variants"
    )
    op.drop_index(op.f("ix_approved_variants_equivalence_set_id"), table_name="approved_variants")
    op.drop_table("approved_variants")
    op.drop_index(
        op.f("ix_product_equivalence_sets_supply_id"), table_name="product_equivalence_sets"
    )
    op.drop_table("product_equivalence_sets")
    op.drop_index(op.f("ix_supplies_beneficiary_id"), table_name="supplies")
    op.drop_table("supplies")
    op.drop_index(op.f("ix_session_tokens_user_id"), table_name="session_tokens")
    op.drop_index(op.f("ix_session_tokens_token_hash"), table_name="session_tokens")
    op.drop_index(op.f("ix_session_tokens_expires_at"), table_name="session_tokens")
    op.drop_table("session_tokens")
    op.drop_index(op.f("ix_merchant_authorizations_owner_id"), table_name="merchant_authorizations")
    op.drop_table("merchant_authorizations")
    op.drop_index(op.f("ix_beneficiaries_owner_id"), table_name="beneficiaries")
    op.drop_table("beneficiaries")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
